[package]
name = "mcp251863"
version = "0.1.0"
edition = "2021"

[dependencies]
arbitrary-int = "1.3.0"
bitbybit = { version = "1.3.3", default-features = false }
embedded-hal = "1.0.0"
crc = "3.2.1"
